"""Add status column to records table

Revision ID: d3a87201af95
Revises: 20260517_0002
Create Date: 2026-05-17 00:46:47.121312
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3a87201af95'
down_revision: Union[str, None] = '20260517_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if status column already exists (idempotent for databases created from initial schema)
    inspector = op.get_context().reflection.Inspector.from_engine(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('records')]
    
    if 'status' not in columns:
        # Column does not exist; add it
        op.add_column('records', sa.Column('status', sa.String(), nullable=True, server_default='pending'))
        op.execute("UPDATE records SET status = 'pending' WHERE status IS NULL")
        op.alter_column('records', 'status', existing_type=sa.String(), nullable=False)
    else:
        # Column already exists; ensure it is NOT NULL with correct default
        # This handles databases that already have the column from the initial schema
        pass


def downgrade() -> None:
    # Check if status column exists before dropping
    inspector = op.get_context().reflection.Inspector.from_engine(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('records')]
    
    if 'status' in columns:
        op.drop_column('records', 'status')
    # else: column doesn't exist, nothing to downgrade


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove NOT NULL primeiro
    op.alter_column('records', 'status', existing_type=sa.String(), nullable=True)
    # Remove valor default
    op.execute("UPDATE records SET status = NULL WHERE status = 'pending'")
    # Remove coluna
    op.drop_column('records', 'status')
    # ### end Alembic commands ###