"""Add status column to records table

Revision ID: d3a87201af95
Revises: 20260517_0002
Create Date: 2026-05-17 00:46:47.121312
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3a87201af95'
down_revision: Union[str, None] = '20260517_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona coluna status como nullable primeiro
    op.add_column('records', sa.Column('status', sa.String(), nullable=True))
    # Atualiza registros existentes com valor padrão 'pending'
    op.execute("UPDATE records SET status = 'pending' WHERE status IS NULL")
    # Define coluna como NOT NULL
    op.alter_column('records', 'status', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove NOT NULL primeiro
    op.alter_column('records', 'status', existing_type=sa.String(), nullable=True)
    # Remove valor default
    op.execute("UPDATE records SET status = NULL WHERE status = 'pending'")
    # Remove coluna
    op.drop_column('records', 'status')
    # ### end Alembic commands ###